#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, os, re

import unittest


from imdb.tests.api import *
from imdb.tests.models import *
from imdb.tests.scraper import *


if __name__ == "__main__":
    unittest.main()
